name: DEPLOY CODE
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master
    
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./src/*
          host: web.techtucson.com
          remote: /var/lib/docker/volumes/WebURData/_data/
          port: 22
          user: webdeploy_ansible
          key: ${{ secrets.DEPLOY_KEY }}
